const channel = {
  // 测试场
  TEST_FIELD: 'TEST_FIELD',

  REPLACE_CLOSE: 'REPLACE_CLOSE',
  REPLACE_REPLACE: 'REPLACE_REPLACE',
  REPLACE_FIND: 'REPLACE_FIND',
  REPLACE_RESET_PREF: 'REPLACE_RESET_PREF',

  // 生成表格
  TABLE_GENERATE: 'TABLE_GENERATE',
  TABLE_GENERATE_FROM_JSON: 'TABLE_GENERATE_FROM_JSON',
  TABLE_CLEAR_HISTORY: 'TABLE_CLEAR_HISTORY',
  GLOBAL_SYSTEM_INFO: 'GLOBAL_SYSTEM_INFO',
};
export default channel;
export type ChannelType = keyof typeof channel;
